use std::fmt::{Display, Formatter};
use serde::Serialize;

#[macro_export]
macro_rules! features {
        ($($feature:expr),* $(,)?) => {
            {
                #[allow(unused_mut)]
                let mut set = HashSet::new();
                $(
                    set.insert($feature);
                )*
                set
            }
        };
    }

#[derive(Clone, PartialEq, Eq, Hash, Debug, Serialize)]
pub enum CardFeature {
    DoubleCrush,
    TripleCrush,
    DiscardOpponent,
    RandomDiscard,
    Draw,
    Assassin,
    Freeze,
    Drop,
    // DeckAttack,
    OnDrop,
    OnRefresh,
    Lancer,
    SLancer,
    Penetrate,
    NonAttackable,
    Down,
    Up,
    Charge,
    EnerAttack,
    Trash,
    Ener,
    PowerUp,
    PowerDown,
    Bounce,
    DeckBounce,
    Salvage,
    LifeBurst,
    Shadow,
    Invulnerable,
    OnSpell,
    OnArts,
    OnPiece,
    OnBanish,
    Banish,
    Guard,
    OnGuard,
    AttackNoEffect,
    OnAttack,
    OnAttackStart,
    OnTouch,
    Awake,
    Exceed,
    OnExceed,
    AddLife,
    OnBurst,
    LifeTrash,
    LifeCrush,
    Damage,
    OnLifeCrush,
    Position,
    Vanilla,
    Untouchable,
    // アークゲイン
    TopCheck,
    BottomCheck,
    Barrier,
    MultiEner,
    LrigTrash,
    Charm,
    Craft,
    Acce,
    Rise,
    Recollect,
    SeekTop,
    EraseSkill
}

impl Display for CardFeature {
    #[allow(unreachable_patterns)]
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let label = match self {
            CardFeature::DoubleCrush => "ダブルクラッシュ",
            CardFeature::TripleCrush => "トリプルクラッシュ",
            CardFeature::DiscardOpponent => "手札破壊",
            CardFeature::RandomDiscard => "ランダム手札破壊",
            CardFeature::Draw => "ドロー",
            CardFeature::Assassin => "アサシン",
            CardFeature::Freeze => "凍結",
            CardFeature::Drop => "デッキドロップ", // DeckAttack,
            CardFeature::OnDrop => "デッキドロップ時",
            CardFeature::OnRefresh => "リフレッシュ時",
            CardFeature::Lancer => "ランサー",
            CardFeature::SLancer => "Sランサー",
            CardFeature::Penetrate => "ガード不可",
            CardFeature::NonAttackable => "アタック不可",
            CardFeature::Down => "ダウン",
            CardFeature::Up => "アップ",
            CardFeature::Charge => "エナチャージ",
            CardFeature::EnerAttack => "エナ破壊",
            CardFeature::Trash => "トラッシュ送り",
            CardFeature::Ener => "エナ送り",
            CardFeature::PowerUp => "パワーアップ",
            CardFeature::PowerDown => "パワーダウン",
            CardFeature::Bounce => "バウンス",
            CardFeature::DeckBounce => "デッキバウンス",
            CardFeature::Salvage => "回収",
            CardFeature::LifeBurst => "ライフバースト",
            CardFeature::Shadow => "シャドウ",
            CardFeature::Invulnerable => "バニッシュされない",
            CardFeature::OnSpell => "スペル使用時",
            CardFeature::OnArts => "アーツ使用時",
            CardFeature::OnPiece => "ピース使用時",
            CardFeature::OnBanish => "バニッシュした時",
            CardFeature::Banish => "バニッシュ",
            CardFeature::Guard => "ガード",
            CardFeature::OnGuard => "ガードした時",
            CardFeature::AttackNoEffect => "アタック無効",
            CardFeature::OnAttack => "アタック時",
            CardFeature::OnAttackStart => "アタック開始時",
            CardFeature::OnTouch => "対象になった時",
            CardFeature::Awake => "覚醒",
            CardFeature::Exceed => "エクシード",
            CardFeature::OnExceed => "エクシードした時",
            CardFeature::AddLife => "ライフクロス追加",
            CardFeature::OnBurst => "ライフバースト発動時",
            CardFeature::LifeTrash => "ライフクロストラッシュ送り",
            CardFeature::LifeCrush => "クラッシュ",
            CardFeature::Damage => "ダメージ",
            CardFeature::OnLifeCrush => "クラッシュ時",
            CardFeature::Position => "シグニゾーン移動",
            CardFeature::Vanilla => "能力を持たない",
            CardFeature::Untouchable => "効果を受けない", // アークゲイン
            CardFeature::TopCheck => "トップ確認",
            CardFeature::BottomCheck => "ボトム確認",
            CardFeature::Barrier => "バリア獲得",
            CardFeature::MultiEner => "マルチエナ",
            CardFeature::LrigTrash => "ルリグトラッシュ",
            CardFeature::Charm => "チャーム",
            CardFeature::Craft => "クラフト",
            CardFeature::Acce => "アクセ",
            CardFeature::Rise => "ライズ",
            CardFeature::Recollect => "リコレクト",
            CardFeature::SeekTop => "シーク",
            CardFeature::EraseSkill => "能力消去",
            _ => "未処理フィーチャー"
        };
        write!(f, "{}", label)
    }
}

impl CardFeature {
    pub fn to_bit(&self) -> u64 {
        match self {
            CardFeature::DoubleCrush => 1_u64,
            CardFeature::TripleCrush => 1 << 1,
            CardFeature::DiscardOpponent => 1 << 2,
            CardFeature::RandomDiscard => 1 << 3,
            CardFeature::Draw => 1 << 4,
            CardFeature::Assassin => 1 << 5,
            CardFeature::Freeze => 1 << 6,
            CardFeature::Drop => 1 << 7,
            // CardFeature::// DeckAttack => 1 << ,
            CardFeature::OnDrop => 1 << 8,
            CardFeature::OnRefresh => 1 << 9,
            CardFeature::Lancer => 1 << 10,
            CardFeature::SLancer => 1 << 11,
            CardFeature::Penetrate => 1 << 12,
            CardFeature::NonAttackable => 1 << 13,
            CardFeature::Down => 1 << 14,
            CardFeature::Up => 1 << 15,
            CardFeature::Charge => 1 << 16,
            CardFeature::EnerAttack => 1 << 17,
            CardFeature::Trash => 1 << 18,
            CardFeature::Ener => 1 << 19,
            CardFeature::PowerUp => 1 << 20,
            CardFeature::PowerDown => 1 << 21,
            CardFeature::Bounce => 1 << 22,
            CardFeature::DeckBounce => 1 << 23,
            CardFeature::Salvage => 1 << 24,
            CardFeature::LifeBurst => 1 << 25,
            CardFeature::Shadow => 1 << 26,
            CardFeature::Invulnerable => 1 << 27,
            CardFeature::OnSpell => 1 << 28,
            CardFeature::OnArts => 1 << 29,
            CardFeature::OnPiece => 1 << 30,
            CardFeature::OnBanish => 1 << 31,
            CardFeature::Banish => 1 << 32,
            CardFeature::Guard => 1 << 33,
            CardFeature::OnGuard => 1 << 34,
            CardFeature::AttackNoEffect => 1 << 35,
            CardFeature::OnAttack => 1 << 36,
            CardFeature::OnAttackStart => 1 << 37,
            CardFeature::OnTouch => 1 << 38,
            CardFeature::Awake => 1 << 39,
            CardFeature::Exceed => 1 << 40,
            CardFeature::OnExceed => 1 << 41,
            CardFeature::AddLife => 1 << 42,
            CardFeature::OnBurst => 1 << 43,
            CardFeature::LifeTrash => 1 << 44,
            CardFeature::LifeCrush => 1 << 45,
            CardFeature::Damage => 1 << 46,
            CardFeature::OnLifeCrush => 1 << 47,
            CardFeature::Position => 1 << 48,
            CardFeature::Vanilla => 1 << 49,
            CardFeature::Untouchable => 1 << 50,
            // CardFeature::// アークゲイ => 1 << ,
            CardFeature::TopCheck => 1 << 51,
            CardFeature::BottomCheck => 1 << 52,
            CardFeature::Barrier => 1 << 53,
            CardFeature::MultiEner => 1 << 54,
            CardFeature::LrigTrash => 1 << 55,
            CardFeature::Charm => 1 << 56,
            CardFeature::Craft => 1 << 57,
            CardFeature::Acce => 1 << 58,
            CardFeature::Rise => 1 << 59,
            CardFeature::Recollect => 1 << 60,
            CardFeature::SeekTop => 1 << 61,
            CardFeature::EraseSkill => 1 << 62,
        }
    }
}
